name: SenkyoSystem
main: senkyo\senkyo
version: 1.0.0
api: 3.7.0
load: POSTWORLD
author: soradore
authors: [narapon]
description: touhyou senkyo plugin
commands:
 senkyo:
  description: "<OP>選挙を開始、終了"
  permission: "senkyo.cmd" 
 senkyori:
  description: "立候補する"
 senkyode:
  description: "立候補を取り下げます"
 senkyot:
  description: "投票する"
 senkyos:
  description: "立候補者一覧"
 senkyodelall:
  description: "<OP>選挙のデータ削除"
  permission: "delall.cmd"
  
permissions:
 senkyo.cmd:
  default: op
 delall.cmd:
  default: op
